on:
  push:
    branches:
      - main
      - ci
      - hotshot-integration
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Repo
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        uses: docker/metadata-action@v4
        id: zkevm-node
        with:
          images: ghcr.io/${{ github.repository_owner }}/zkevm-node

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.zkevm-node.outputs.tags }}
          labels: ${{ steps.zkevm-node.outputs.labels }}

      - name: Generate docker metadata
        uses: docker/metadata-action@v4
        id: zkprover-mock
        with:
          images: ghcr.io/${{ github.repository_owner }}/zkprover-mock

      - name: Build and push zkevmprovermock
        id: docker_build_zkevmprovermock
        uses: docker/build-push-action@v4
        with:
          context: .
          file: tools/zkevmprovermock/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.zkprover-mock.outputs.tags }}
          labels: ${{ steps.zkprover-mock.outputs.labels }}
